apiVersion: v2
name: forensic-platform
description: Helm chart for Nexus Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: "12.x.x"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
- name: redis
  version: "17.x.x"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled
- name: rabbitmq
  version: "11.x.x"
  repository: "https://charts.bitnami.com/bitnami"
  condition: rabbitmq.enabled
- name: minio
  version: "12.x.x"
  repository: "https://charts.bitnami.com/bitnami"
  condition: minio.enabled
- name: elasticsearch
  version: "19.x.x"
  repository: "https://charts.elastic.co"
  condition: elasticsearch.enabled
- name: kibana
  version: "19.x.x"
  repository: "https://charts.elastic.co"
  condition: kibana.enabled
- name: prometheus
  version: "19.x.x"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: prometheus.enabled
- name: grafana
  version: "6.x.x"
  repository: "https://grafana.github.io/helm-charts"
  condition: grafana.enabled