# Global Values
global:
  environment: production
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: standard

# Namespace Configuration
namespace:
  create: true
  name: forensic-platform

# Common Labels
commonLabels:
  app: forensic-reconciliation
  environment: production

# Main Application
forensicApp:
  image:
    repository: nexus
    tag: enhanced
    pullPolicy: IfNotPresent
  replicaCount: 3
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 4000m
      memory: 4Gi
  persistence:
    logs:
      size: 10Gi
    uploads:
      size: 50Gi
    reports:
      size: 20Gi

# API Gateway
apiGateway:
  image:
    repository: api_gateway
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

# Microservices
encryptionService:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

hashService:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

chainOfCustodyService:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

dataRetentionService:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

gdprService:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

# Dependencies Configuration
postgresql:
  enabled: true
  auth:
    username: forensic_prod_user
    database: forensic_reconciliation_prod
  primary:
    persistence:
      size: 20Gi

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
  master:
    persistence:
      size: 10Gi

rabbitmq:
  enabled: true
  auth:
    username: forensic_user
  persistence:
    size: 8Gi

minio:
  enabled: true
  mode: standalone
  persistence:
    size: 100Gi

elasticsearch:
  enabled: true
  master:
    replicaCount: 1
    persistence:
      size: 30Gi

kibana:
  enabled: true

prometheus:
  enabled: true
  server:
    retention: 15d
    persistentVolume:
      size: 50Gi

grafana:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi

# Istio Configuration
istio:
  enabled: true
  gateway:
    enabled: true
    hosts:
      - "*"

# HPA Configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80