# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Jul 13 06:44:10 2024
# ------------------------------------------------

package:
  name: icu
  version: '75.1'
source:
  - patches:
      - mach-port-t.patch
    sha256: cb968df3e4d2e87e8b11c49a5d01c787bd13b9545280fc6642f826527618caef
    url: https://github.com/unicode-org/icu/releases/download/release-75-1/icu4c-75_1-src.tgz
  - folder: source/data
    sha256: a5104212dc317a64f9b035723ea706f2f4fd5a0f37b7923fae7aeb9d1d0061b1
    url: https://github.com/unicode-org/icu/releases/download/release-75-1/icu4c-75_1-data.zip
build:
  number: '0'
  run_exports:
    - icu >=75.1,<76.0a0
  string: h120a0e1_0
requirements:
  build:
    - clang_bootstrap_osx-64 16.0.6 h4cad966_17
    - libtool 2.4.7 hf0c8a7f_0
    - macosx_deployment_target_osx-64 10.13 hbc8f3bb_1
    - make 4.3 h22f3db7_1
  host:
    - __osx >=10.13
  run:
    - __osx >=10.13
test:
  commands:
    - test ! -f $PREFIX/lib/libicudata.a
    - test -f $PREFIX/lib/libicudata.75.1.dylib
    - test ! -f $PREFIX/lib/libicui18n.a
    - test -f $PREFIX/lib/libicui18n.75.1.dylib
    - test ! -f $PREFIX/lib/libicuio.a
    - test -f $PREFIX/lib/libicuio.75.1.dylib
    - test ! -f $PREFIX/lib/libicutest.a
    - test -f $PREFIX/lib/libicutest.75.1.dylib
    - test ! -f $PREFIX/lib/libicutu.a
    - test -f $PREFIX/lib/libicutu.75.1.dylib
    - test ! -f $PREFIX/lib/libicuuc.a
    - test -f $PREFIX/lib/libicuuc.75.1.dylib
    - genbrk --help
    - gencfu --help
    - gencnval --help
    - gendict --help
    - icuinfo --help
    - icu-config --help
    - makeconv gb-18030-2000.ucm
  files:
    - de.txt
    - gb-18030-2000.ucm
about:
  dev_url: https://github.com/unicode-org/icu
  doc_url: https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/
  home: https://icu.unicode.org
  license: MIT
  license_file: LICENSE
  summary: International Components for Unicode.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240713.1.1
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - xhochy
  remote_url: https://github.com/conda-forge/icu-feedstock
  sha: dc39a238c7b171624dee6c0f1b0765e3a6abe868
