// This file serves as the public API for our shared types package.
// We are re-exporting the types generated by Prisma, which is our single source of truth.

import type { 
    User, 
    Case, 
    Transaction, 
    ColumnMappingTemplate,
    Discrepancy,
    Evidence,
    MatchingResult,
    ReconciliationJob,
    FraudAlert,
    AuditLog,
    CaseSnapshot
} from '@prisma/client';

export type {
    User,
    Case,
    Transaction,
    ColumnMappingTemplate,
    Discrepancy,
    Evidence,
    MatchingResult,
    ReconciliationJob,
    FraudAlert,
    AuditLog,
    CaseSnapshot
};

// WebSocket Event Payloads
export interface AnalysisStarted {
    caseId: string;
}

export interface AnalysisProgress {
    caseId: string;
    progress: number;
}

export interface AnalysisComplete {
    caseId: string;
    results: unknown;
}

export interface MatchResultPayload {
    id: string;
    transactionA: Transaction;
    transactionB: Transaction;
    rationale: string;
}

export interface UnmatchResultPayload {
    transaction: Transaction;
}