# This file created by conda-build 24.5.0
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cfobk8lkrt/clone/recipe, last modified Thu Aug  1 10:17:49 2024
# ------------------------------------------------

package:
  name: libxslt
  version: 1.1.41
source:
  fn: libxslt-1.1.41.tar.xz
  sha256: 3ad392af91115b7740f7b50d228cc1c5fc13afc1da7f16cb0213917a37f71bda
  url: https://download.gnome.org/sources/libxslt/1.1/libxslt-1.1.41.tar.xz
build:
  number: '0'
  run_exports:
    - libxslt >=1.1.41,<2.0a0
  string: ha190046_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - gnuconfig 2021.05.24 hd3eb1b0_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libiconv 1.16 h6c40b1e_3
    - libllvm14 14.0.6 h91fad77_3
    - llvm-tools 14.0.6 he0576d7_3
    - make 4.2.1 h3efe00b_1
    - pkg-config 0.29.2 h3efe00b_8
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4b97444_1
  host:
    - icu 73.1 hcec6c5f_0
    - libcxx 14.0.6 h9765a3e_0
    - libiconv 1.16 h6c40b1e_3
    - libxml2 2.13.1 h6070cd6_2
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - libxml2 >=2.13.1,<2.14.0a0
test:
  commands:
    - xsltproc --version
    - pkg-config --cflags libxslt libexslt
    - pkg-config --libs libxslt libexslt
  requires:
    - pkg-config
about:
  description: '"Libxslt is the XSLT C library developed for the GNOME project.

    XSLT itself is a an XML language to define transformation for XML.

    Libxslt is based on libxml2 the XML C library developed for the GNOME project.

    It also implements most of the EXSLT set of processor-portable extensions functions

    and some of Saxon''s evaluate and expressions extensions."

    '
  dev_url: https://gitlab.gnome.org/GNOME/libxslt
  doc_url: https://gitlab.gnome.org/GNOME/libxslt/-/wikis
  home: https://gitlab.gnome.org/GNOME/libxslt
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: The XSLT C library developed for the GNOME project
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: cf5c5221-5515-415e-a02b-0379b1a2a120
  recipe-maintainers:
    - chenghlee
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/libxslt-feedstock.git
  sha: c8776ee7fcdf8b4faf863a4e79cd2fdcb646d68e
