CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
MACOSX_DEPLOYMENT_TARGET: '10.9'
VERBOSE_AT: V=1
c_compiler: clang
c_compiler_version: '15'
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
cxx_compiler_version: '15'
extend_keys:
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
- ignore_version
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
krb5: '1.21'
lua: '5'
macos_machine: x86_64-apple-darwin13.4.0
numpy: '1.22'
openssl: '3'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.10'
r_base: '3.5'
target_platform: osx-64
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
