# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Jul 22 21:21:54 2023
# ------------------------------------------------

package:
  name: cyrus-sasl
  version: 2.1.27
source:
  patches:
    - osx_arm.patch
  sha256: b564d773803dc4cff42d2bdc04c80f2b105897a724c247817d4e4a99dd6b9976
  url: https://github.com/cyrusimap/cyrus-sasl/archive/cyrus-sasl-2.1.27.tar.gz
build:
  missing_dso_whitelist:
    - /usr/lib/libpam.2.dylib
    - /usr/lib/libresolv.9.dylib
  number: '7'
  run_exports:
    - cyrus-sasl >=2.1.27,<3.0a0
  string: hf9bab2b_7
requirements:
  build:
    - autoconf 2.71 pl5321hed12c24_1
    - automake 1.16.5 pl5321h694c41f_0
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 h48a5a9d_13
    - clang 15.0.7 h694c41f_2
    - clang-15 15.0.7 default_hdb78580_2
    - clang_osx-64 15.0.7 h03d6864_3
    - clangxx 15.0.7 default_hdb78580_2
    - clangxx_osx-64 15.0.7 h2133e9c_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - groff 1.22.4 pl5321haade3ac_1
    - icu 72.1 h7336db1_0
    - ld64_osx-64 609 h8ce0179_13
    - libclang-cpp15 15.0.7 default_hdb78580_2
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_2
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.11.4 hd95e348_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_2
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - openssl 3.1.1 h8a1eda9_1
    - perl 5.32.1 4_h0dc2134_perl5
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 h829000d_7
  host:
    - ca-certificates 2023.7.22 h8857fd0_0
    - krb5 1.21.1 hb884880_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libntlm 1.4 h0d85af4_1002
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.1 h8a1eda9_1
  run:
    - krb5 >=1.21.1,<1.22.0a0
    - libcxx >=15.0.7
    - libntlm
    - openssl >=3.1.1,<4.0a0
test:
  commands:
    - echo "DONE"
about:
  description: 'Simple Authentication and Security Layer (SASL) is a specification
    that describes how

    authentication mechanisms can be plugged into an application protocol on the wire.
    Cyrus

    SASL is an implementation of SASL that makes it easy for application developers
    to integrate

    authentication mechanisms into their application in a generic way.

    '
  dev_url: https://github.com/cyrusimap/cyrus-sasl
  doc_url: https://www.cyrusimap.org/sasl/
  home: https://www.cyrusimap.org/sasl/
  license: BSD-3-Clause-Attribution
  license_family: BSD
  license_file: COPYING
  summary: 'This is the Cyrus SASL API implementation. It can be used on the client
    or server side to provide

    authentication and authorization services. See RFC 4422 for more information.

    '
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - StephenSmith25
    - mariusvniekerk
    - martindurant
    - mingwandroid
    - wesm
