apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
  namespace: forensic-platform
type: Opaque
data:
  password: U2VjdXJlTmVvNGpQYXNzd29yZDIwMjQh # SecureNeo4jPassword2024!
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: forensic-platform
data:
  neo4j.conf: |
    dbms.security.auth_enabled=true
    dbms.memory.heap.initial_size=512m
    dbms.memory.heap.max_size=1g
    dbms.memory.pagecache.size=512m
    dbms.default_database=forensic
    dbms.security.procedures.unrestricted=apoc.*
    dbms.security.procedures.allowlist=apoc.*
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: forensic-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-logs-pvc
  namespace: forensic-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: forensic-platform
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.11-enterprise
        env:
        - name: NEO4J_AUTH
          value: neo4j/$(NEO4J_PASSWORD)
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-secret
              key: password
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7473
          name: https
        - containerPort: 7687
          name: bolt
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
        - name: neo4j-config
          mountPath: /conf/neo4j.conf
          subPath: neo4j.conf
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data-pvc
      - name: neo4j-logs
        persistentVolumeClaim:
          claimName: neo4j-logs-pvc
      - name: neo4j-config
        configMap:
          name: neo4j-config
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: forensic-platform
spec:
  selector:
    app: neo4j
  ports:
  - name: http
    port: 7474
    targetPort: 7474
  - name: https
    port: 7473
    targetPort: 7473
  - name: bolt
    port: 7687
    targetPort: 7687
  type: ClusterIP