apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: forensic-platform
type: Opaque
data:
  username: Zm9yZW5zaWNfdXNlcg== # forensic_user
  password: U2VjdXJlUmFiYml0TVFQYXNzd29yZDIwMjQh # SecureRabbitMQPassword2024!
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: forensic-platform
data:
  rabbitmq.conf: |
    default_vhost = forensic_vhost
    default_user = $(RABBITMQ_DEFAULT_USER)
    default_pass = $(RABBITMQ_DEFAULT_PASS)
    management.load_definitions = /etc/rabbitmq/definitions.json
  definitions.json: |
    {
      "vhosts": [
        {"name": "forensic_vhost"}
      ],
      "permissions": [
        {
          "user": "forensic_user",
          "vhost": "forensic_vhost",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ]
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: forensic-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: forensic-platform
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/definitions.json
          subPath: definitions.json
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "ping"]
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_port_connectivity"]
          initialDelaySeconds: 20
          periodSeconds: 30
      volumes:
      - name: rabbitmq-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
      - name: rabbitmq-config
        configMap:
          name: rabbitmq-config
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: forensic-platform
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  type: ClusterIP