{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "forensic-platform.apiGateway.fullname" . }}-config
  labels:
    {{- include "forensic-platform.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.global.environment | quote }}
  PORT: {{ .Values.apiGateway.service.port | quote }}
  REDIS_HOST: {{ .Release.Name }}-redis-master
  REDIS_PORT: "6379"
  RABBITMQ_HOST: {{ .Release.Name }}-rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: {{ .Values.rabbitmq.vhost | quote }}
  POSTGRES_HOST: {{ .Release.Name }}-postgresql
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  NEO4J_HOST: {{ .Release.Name }}-neo4j
  NEO4J_PORT: "7687"
  MINIO_HOST: {{ .Release.Name }}-minio
  MINIO_PORT: "9000"
  AI_SERVICE_URL: "http://{{ include "forensic-platform.aiService.fullname" . }}:8000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forensic-platform.apiGateway.fullname" . }}
  labels:
    {{- include "forensic-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway
      {{- include "forensic-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: api-gateway
        {{- include "forensic-platform.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api-gateway.yaml") . | sha256sum }}
    spec:
      {{- with .Values.apiGateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.apiGateway.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-api-gateway
          securityContext:
            {{- toYaml .Values.apiGateway.securityContext | nindent 12 }}
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiGateway.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "forensic-platform.apiGateway.fullname" . }}-config
            - secretRef:
                name: {{ .Release.Name }}-postgresql
            - secretRef:
                name: {{ .Release.Name }}-redis
            - secretRef:
                name: {{ .Release.Name }}-rabbitmq
            - secretRef:
                name: {{ .Release.Name }}-neo4j
            - secretRef:
                name: {{ .Release.Name }}-minio
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
      {{- with .Values.apiGateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "forensic-platform.apiGateway.fullname" . }}
  labels:
    {{- include "forensic-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: api-gateway
    {{- include "forensic-platform.selectorLabels" . | nindent 4 }}
---
{{- if .Values.apiGateway.ingress.enabled }}
apiVersion: {{ include "forensic-platform.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "forensic-platform.apiGateway.fullname" . }}
  labels:
    {{- include "forensic-platform.labels" . | nindent 4 }}
  {{- with .Values.apiGateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.apiGateway.ingress.className }}
  ingressClassName: {{ .Values.apiGateway.ingress.className }}
  {{- end }}
  {{- if .Values.apiGateway.ingress.tls }}
  tls:
    {{- range .Values.apiGateway.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.apiGateway.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "forensic-platform.apiGateway.fullname" $ }}
                port:
                  number: {{ $.Values.apiGateway.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}