{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "forensic-platform.apiGateway.fullname" . }}
  labels:
    {{- include "forensic-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: api-gateway
      {{- include "forensic-platform.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.apiGateway.service.port }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: ai-service
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: rabbitmq
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: neo4j
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: minio
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "forensic-platform.aiService.fullname" . }}
  labels:
    {{- include "forensic-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: ai-service
      {{- include "forensic-platform.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: rabbitmq
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: neo4j
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: minio
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}