#
# Configuration file for using the xslt library
#
XSLT_LIBDIR="-L/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cfobk8lkrt/croot/libxslt_1722525477737/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib"
XSLT_LIBS="-lxslt -L/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cfobk8lkrt/croot/libxslt_1722525477737/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -lxml2 "
XSLT_PRIVATE_LIBS=""
XSLT_INCLUDEDIR="-I/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cfobk8lkrt/croot/libxslt_1722525477737/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include"
MODULE_VERSION="xslt-1.1.41"
