version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    compress: "true"

x-monitoring: &default-monitoring
  - prometheus
  - grafana
  - elasticsearch
  - kibana

x-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

x-resources: &default-resources
  limits:
    memory: 1G
    cpus: '1.0'
  reservations:
    memory: 512M
    cpus: '0.5'

services:
  # MinIO Object Storage with Enhanced Logging
  minio:
    image: minio/minio:latest
    container_name: forensic_minio_enhanced
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-forensic_user}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-secure_password_123}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL:-https://minio.forensic.com}
      - MINIO_LOG_LEVEL=info
      - MINIO_AUDIT_WEBHOOK_ENABLE=on
      - MINIO_AUDIT_WEBHOOK_ENDPOINT=http://elasticsearch:9200
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9001" --address ":9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      <<: *default-healthcheck
    restart: unless-stopped
    logging: *default-logging
    networks:
      - forensic_network
    labels:
      - "com.forensic.service=storage"
      - "com.forensic.tier=data"
      - "com.forensic.monitoring=true"
