# Default values for forensic-platform chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

# Service definitions
aiService:
  image: forensic_reconciliation_app-ai_service:dev
  pullPolicy: IfNotPresent
  port: 8000
  replicaCount: 1
  resources: {}

apiGateway:
  image: forensic_reconciliation_app-api_gateway:dev
  pullPolicy: IfNotPresent
  port: 3000
  replicaCount: 1
  resources: {}

postgres:
  image: postgres:15-alpine
  port: 5432
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
  resources: {}

redis:
  image: redis:7-alpine
  port: 6379
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""
  resources: {}

minio:
  image: minio/minio:latest
  apiPort: 9000
  consolePort: 9001
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  resources: {}

rabbitmq:
  image: rabbitmq:3-management-alpine
  amqpPort: 5672
  managementPort: 15672
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""
  resources: {}

neo4j:
  image: neo4j:5-community
  httpPort: 7474
  boltPort: 7687
  persistence:
    data:
      enabled: true
      size: 10Gi
      storageClass: ""
    logs:
      enabled: true
      size: 1Gi
      storageClass: ""
    import:
      enabled: true
      size: 1Gi
      storageClass: ""
  resources: {}

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
  port: 9200
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  resources: {}

kibana:
  image: docker.elastic.co/kibana/kibana:8.11.0
  port: 5601
  resources: {}

prometheus:
  image: prom/prometheus:latest
  port: 9090
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""
  resources: {}

grafana:
  image: grafana/grafana:latest
  port: 3000
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""
  resources: {}

config:
  # This will be populated from the configmap
  data: {}

secret:
  # This will be populated from the secret
  stringData: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
