x86_64_opt:
  - none
  - v2                         # [(x86 or x86_64) and not osx]
  - v3                         # [(x86 or x86_64) and not osx]
blas_impl:
  - mkl                        # [(x86 or x86_64) and not osx]
  - openblas                   # [not win and not osx]
  - accelerate                 # [osx]
  - cublas                     # [win or (linux and x86_64)]

gpu_variant:
  - none
  - metal                      # [osx and arm64]
  - cuda-11                    # [linux and x86_64]
  - cuda-12                    # [win or (linux and x86_64)]

cuda_compiler_version:         # [win or (linux and x86_64)]
  - none                       # [win or (linux and x86_64)]
  - 11.8                       # [(linux and x86_64)]
  - 12.4                       # [win or (linux and x86_64)]

cuda_compiler:                 # [win or (linux and x86_64)]
- cuda-nvcc                    # [win or (linux and x86_64)]

zip_keys:                      # [win or (linux and x86_64)]
  -                            # [win or (linux and x86_64)]
    - gpu_variant              # [win or (linux and x86_64)]
    - cuda_compiler_version    # [win or (linux and x86_64)]