apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: forensic-app
  labels:
    app: ai-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: ai-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: forensic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: forensic_reconciliation_app-ai_service:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: forensic-config
            - secretRef:
                name: forensic-secret
          ports:
            - containerPort: 8000
