apiVersion: v1
kind: Namespace
metadata:
  name: forensic-reconciliation
  labels:
    name: forensic-reconciliation
    app: forensic-reconciliation
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: forensic-reconciliation-quota
  namespace: forensic-reconciliation
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
