apiVersion: v1
kind: Service
metadata:
  name: {{ include "forensic-platform.fullname" . }}-elasticsearch
  namespace: {{ .Release.Namespace }}
  labels:
    app: elasticsearch
    {{- include "forensic-platform.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
  selector:
    app: elasticsearch
    {{- include "forensic-platform.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forensic-platform.fullname" . }}-elasticsearch
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.elasticsearch.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: elasticsearch
      {{- include "forensic-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: elasticsearch
        {{- include "forensic-platform.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image }}"
          imagePullPolicy: {{ .Values.elasticsearch.pullPolicy | default "IfNotPresent" }}
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
          ports:
            - containerPort: {{ .Values.elasticsearch.port }}
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: {{ include "forensic-platform.fullname" . }}-elasticsearch-pvc
---
{{- if .Values.elasticsearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "forensic-platform.fullname" . }}-elasticsearch-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.elasticsearch.persistence.size }}
  {{- if .Values.elasticsearch.persistence.storageClass }}
  storageClassName: {{ .Values.elasticsearch.persistence.storageClass }}
  {{- end }}
{{- end }}
