apiVersion: v1
kind: Service
metadata:
  name: {{ include "forensic-platform.fullname" . }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
    {{- include "forensic-platform.labels" . | nindent 4 }}
spec:
  ports:
    - name: api
      port: {{ .Values.minio.apiPort }}
      targetPort: {{ .Values.minio.apiPort }}
    - name: console
      port: {{ .Values.minio.consolePort }}
      targetPort: {{ .Values.minio.consolePort }}
  selector:
    app: minio
    {{- include "forensic-platform.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forensic-platform.fullname" . }}-minio
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.minio.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: minio
      {{- include "forensic-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: minio
        {{- include "forensic-platform.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image }}"
          imagePullPolicy: {{ .Values.minio.pullPolicy | default "IfNotPresent" }}
          command:
            - "server"
            - "/data"
            - "--console-address"
            - ":{{ .Values.minio.consolePort }}"
          envFrom:
            - configMapRef:
                name: {{ include "forensic-platform.fullname" . }}-config
            - secretRef:
                name: {{ include "forensic-platform.fullname" . }}-secret
          ports:
            - containerPort: {{ .Values.minio.apiPort }}
            - containerPort: {{ .Values.minio.consolePort }}
          volumeMounts:
            - name: minio-data
              mountPath: /data
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: {{ include "forensic-platform.fullname" . }}-minio-pvc
---
{{- if .Values.minio.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "forensic-platform.fullname" . }}-minio-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
  {{- if .Values.minio.persistence.storageClass }}
  storageClassName: {{ .Values.minio.persistence.storageClass }}
  {{- end }}
{{- end }}
