# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a2f1cd4c-a54a-4fd7-4d41-89e49df7262d/volume/rsync-recipes/libntlm-1.6-on-osx, last modified Thu Sep 16 17:11:04 2021
# ------------------------------------------------

package:
  name: libntlm
  version: '1.6'
source:
  fn: libntlm-1.6.tar.gz
  sha256: f2376b87b06d8755aa3498bb1226083fdb1d2cf4460c3982b05a9aa0b51d6821
  url: http://www.nongnu.org/libntlm/releases/libntlm-1.6.tar.gz
build:
  number: '0'
  run_exports:
    - libntlm >=1.6,<2.0a0
  string: h9ed2024_0
requirements:
  build:
    - cctools 927.0.2 h5ba7a2e_4
    - clang 10.0.0 default_hf57f61e_0
    - clang_osx-64 10.0.0 h05bbb7f_1
    - clangxx 10.0.0 default_hf57f61e_0
    - compiler-rt 10.0.0 h47ead80_0
    - compiler-rt_osx-64 10.0.0 hbcc88fd_0
    - ld64 450.3 h3c32e8a_4
    - libcxx 12.0.0 h2f01273_0
    - libllvm10 10.0.0 h21ff451_2
    - libtool 2.4.6 haf1e3a3_1005
    - llvm-openmp 10.0.0 h28b9765_0
    - llvm-tools 10.0.0 h21ff451_2
    - make 4.2.1 h3efe00b_1
    - tapi 1000.10.8 ha1b3eb9_0
  run: []
test:
  commands:
    - test -f $PREFIX/include/ntlm.h
    - test -f $PREFIX/lib/libntlm.a
    - test -f $PREFIX/lib/libntlm.dylib
    - test -f $PREFIX/lib/libntlm.0.dylib
    - test -f $PREFIX/lib/pkgconfig/libntlm.pc
about:
  home: http://www.nongnu.org/libntlm/
  license: LGPL-2.1
  license_file: COPYING
  summary: Improved implementation of Microsoft's NTLM authentication
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - katietz
    - koverholt
    - mariusvniekerk
    - martindurant
