# Logstash Configuration for Forensic Platform
# Centralized logging and log processing

http.host: "0.0.0.0"
xpack.monitoring.enabled: false

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Queue settings
queue.type: memory
queue.max_events: 1000

# Logging
log.level: info
log.format: json

# Monitoring
monitoring.enabled: false
