name: Build, Lint, and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Desktop/Nexus/forensic_reconciliation_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai_service/requirements.txt
          pip install pylint black isort pytest

      - name: Install Node.js dependencies
        run: |
          npm ci
        working-directory: ./Desktop/Nexus/forensic_reconciliation_app/api_gateway

      - name: Lint with Pylint
        run: |
          pylint --rcfile=pyproject.toml ai_service/

      - name: Check formatting with Black
        run: |
          black --check --config=pyproject.toml .

      - name: Check import order with isort
        run: |
          isort --check-only --settings-path=pyproject.toml .

      - name: Run tests with Pytest
        run: |
          pytest

      - name: Build Docker images
        run: |
          docker-compose build
