# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_e0nz6k7m8q/clone/recipe, last modified Tue Dec 19 11:16:42 2023
# ------------------------------------------------

package:
  name: libedit
  version: 3.1.20230828
source:
  fn: libedit-20230828-3.1.tar.gz
  patches:
    - 0001-prefer-tinfo-over-curses-and-termcap.patch
  sha256: 4ee8182b6e569290e7d1f44f0f78dac8716b35f656b76528f699c69c98814dad
  url: https://thrysoee.dk/editline/libedit-20230828-3.1.tar.gz
build:
  number: '0'
  run_exports:
    - libedit >=3.1.20230828,<3.2.0a0
  string: h6c40b1e_0
requirements:
  build:
    - autoconf 2.71 pl5340h6c40b1e_0
    - automake 1.16.5 pl5340hecd8cb5_1
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - gdbm 1.18 hdccc71a_4
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_0
    - libiconv 1.16 hca72f7f_2
    - libllvm14 14.0.6 h91fad77_3
    - llvm-tools 14.0.6 he0576d7_3
    - m4 1.4.18 h1de35cc_1
    - make 4.2.1 h3efe00b_1
    - ncurses 6.4 hcec6c5f_0
    - patch 2.7.6 h1de35cc_1001
    - perl 5.34.0 h435f0c2_2
    - pkg-config 0.29.2 h3efe00b_8
    - readline 8.2 hca72f7f_0
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4dc903c_0
  host:
    - ncurses 6.4 hcec6c5f_0
  run:
    - ncurses >=6.4,<7.0a0
test:
  commands:
    - test -f $PREFIX/lib/pkgconfig/libedit.pc
    - test -f $PREFIX/lib/libedit.dylib
about:
  description: 'This is an autotool- and libtoolized port of the NetBSD Editline library

    (libedit). This Berkeley-style licensed command line editor library provides

    generic line editing, history, and tokenization functions, similar to those

    found in GNU Readline

    '
  doc_url: https://thrysoee.dk/editline/
  home: https://thrysoee.dk/editline/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Editline Library (libedit)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e059609a-05f9-49e6-915d-8dae5dd955e2
  recipe-maintainers:
    - djsutherland
    - mingwandroid
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/libedit-feedstock.git
  sha: 7a7d7fa76795c754a54ef5b256c4766d665f6034
